import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split("""
Nuvoton/M3351/Source/startup_M3351.c
Nuvoton/M3351/Source/system_M3351.c
""")

path = [cwd + '/Nuvoton/M3351/Include',]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

Return('group')
